### PR TITLE
Nether fix + Dojo + Blaze Slayer qol + Custom Ability Block

### PR DESCRIPTION
**Pull request by Tadd12**
Fixed Nether Location + one Dojo qol

### CODE REVIEW

**Comment by jxxe** [comment]
Hey @Tadd12, would you mind sending a video of it working? I've started a build so you can just download the JAR when it's finished.

**Comment by Tadd12** [comment]
- Improved Version of OneLemonyBois Dagger swap to work with less code and all daggers
- video of dojo https://youtu.be/8t0gpKWiMZU

**Comment by jxxe** [comment]
> * video of dojo https://youtu.be/8t0gpKWiMZU

The video is private

**Comment by Tadd12** [comment]
Should be fixed. Forgot to change visibility

**Comment by Tadd12** [comment]
Hold the item and press "p" to add/remove the item. In the menu the ability blocking can be toggled and on a button you see all current items and what ability is blocked (rc, lc or both). It gets saved in "shady/abilities.json".

**Comment by Tadd12** [comment]
merge pls

**Pull request closed without merging**
