### PR TITLE
Terms Fix for new terminals

### PR DESCRIPTION
**Pull request by cinqdtun**
Added new terms solver

### CODE REVIEW

**Comment by jxxe** [comment]
I’ll check this out once I’m back from vacation. Could you attach a video of it working?

**Comment by cinqdtun** [comment]
Sure !
[Toggle Color Terminal](https://youtu.be/FsnswkHF3vI)
[Timing Terminal](https://youtu.be/KqkeAsc5LdQ)

**Comment by jxxe** [comment]
The videos look good, but again, it's going to be a little while because I currently don't have access to a computer.

**Comment by cinqdtun** [comment]
No problem !

**Comment by jxxe** [comment]
Do you have a Discord account in the ShadyAddons server so I can give you a special role? Still on vacation for another week or so.

**Comment by cinqdtun** [comment]
Yes i have an account in shady discord.
Enjoy your vacation !

**Comment by gabrielvicenteYT** [comment]
@jxxe Check this again

**Comment by cinqdtun** [comment]
I think the pr is outdated now, if I remember correctly the timing solver doesn't work anymore

**Pull request closed without merging**
